steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - us-central1-docker.pkg.dev/$PROJECT_ID/quorum/frontend:latest
      - --build-arg
      - VITE_WS_URL=${_VITE_WS_URL}
      - --build-arg
      - VITE_API_URL=${_VITE_API_URL}
      - .
images:
  - us-central1-docker.pkg.dev/$PROJECT_ID/quorum/frontend:latest
substitutions:
  _VITE_WS_URL: ws://localhost:8000/ws
  _VITE_API_URL: http://localhost:8000
