steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - gcr.io/$PROJECT_ID/warroom-frontend:latest
      - --build-arg
      - VITE_WS_BASE_URL=${_VITE_WS_BASE_URL}
      - .
images:
  - gcr.io/$PROJECT_ID/warroom-frontend:latest
substitutions:
  _VITE_WS_BASE_URL: ws://localhost:8000
